export const REQUEST_OBJECTS_DATA = 'REQUEST_OBJECTS_DATA';
export const REQUEST_CHOSEN_OBJECT = 'REQUEST_CHOSEN_OBJECT';
export const REQUEST_OBJECTS_DATA_FAILED = 'REQUEST_OBJECTS_DATA_FAILED';
export const GET_INIT_DATA_SUCCEDED = 'GET_INIT_DATA_SUCCEDED';
export const GET_FILTERED_DATA_SUCCEDED = 'GET_FILTERED_DATA_SUCCEDED';
export const SET_FILTER_INPUT_VALUE = 'SET_FILTER_INPUT_VALUE';
export const SET_INITIAL_FILTER_VALUES = 'SET_INITIAL_FILTER_VALUES';
export const GET_CHOSEN_OBJECT_SUCCEDED = 'GET_CHOSEN_OBJECT_SUCCEDED';
