export const REQUEST_OBJECTS_DATA = 'REQUEST_OBJECTS_DATA';
export const REQUEST_CHOSEN_OBJECT = 'REQUEST_CHOSEN_OBJECT';
export const REQUEST_DATA_FAILED = 'REQUEST_DATA_FAILED';
export const REQUEST_INIT_DATA_SUCCEDED = 'REQUEST_INIT_DATA_SUCCEDED';
export const REQUEST_OBJECTS_DATA_SUCCEDED = 'REQUEST_OBJECTS_DATA_SUCCEDED';
export const SET_FILTER_INPUT_VALUE = 'SET_FILTER_INPUT_VALUE';
export const SET_INITIAL_FILTER_VALUES = 'SET_INITIAL_FILTER_VALUES';
export const REQUEST_CHOSEN_OBJECT_SUCCEDED = 'REQUEST_CHOSEN_OBJECT_SUCCEDED';
