export const SETUP_FILTER = 'SETUP_FILTER';
export const SET_TOTAL_OBJECTS = 'SET_TOTAL_OBJECTS';
export const SET_FILTER_INPUT_VALUE = 'SET_FILTER_INPUT_VALUE';
export const SET_INITIAL_FILTER_VALUES = 'SET_INITIAL_FILTER_VALUES';
export const TOGGLE_IS_FETCHING = 'TOGGLE_IS_FETCHING';
